branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: FOOD_DRINK_APP
  branch: main
  default_ec2_keyname: null
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: Food-and-drinks
  sc: git
  workspace_type: Application
